src/Entity/Article.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ApiResource]
#[ORM\Entity(repositoryClass: ArticleRepository::class)]
class Article
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: 'integer')]
    private $id;

    #[ORM\Column(type: 'string', length: 190)]
    private $title;

    #[ORM\Column(type: 'text')]
    private $body;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private $published_at;

    #[Assert\Count(min: 2, max: 5)]
    #[ORM\ManyToMany(targetEntity: Tag::class, inversedBy: 'articles')]
    private $tags;

    #[ORM\ManyToOne(targetEntity: Category::class, inversedBy: 'articles')]
    private $category;

    #[Assert\NotNull]
    #[ORM\ManyToOne(targetEntity: Writer::class, inversedBy: 'articles')]
    private $writer;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeImmutable
    {
        return $this->published_at;
    }

    public function setPublishedAt(?\DateTimeImmutable $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    /**
     * @return Collection<int, Tag>
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getWriter(): ?Writer
    {
        return $this->writer;
    }

    public function setWriter(?Writer $writer): self
    {
        $this->writer = $writer;

        return $this;
    }
}

src/Controller/AdminArticleController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Form\ArticleType;
use App\Repository\ArticleRepository;
use App\Repository\WriterRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

#[Route('/admin/article')]
class AdminArticleController extends AbstractController
{
    private WriterRepository $writerRepository;

    public function __construct(WriterRepository $writerRepository)
    {
        // récupération du writer repository (grâce à l'auto wiring ci-dessus)
        $this->writerRepository = $writerRepository;
    }

    #[Route('/', name: 'app_admin_article_index', methods: ['GET'])]
    public function index(ArticleRepository $articleRepository): Response
    {
        // les utilisateurs non authentifiés sont renvoyés vers la page de login
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        // création d'une liste d'articles vide
        $articles = [];

        if ($this->isGranted('ROLE_EDITOR')) {
            // si l'utilisateur est un éditeur, il peut voir la liste complète
            $articles = $articleRepository->findAll();
        } elseif ($this->isGranted('ROLE_WRITER')) {
            // si l'utilisateur est un rédacteur, il ne peut voir que ses articles
            // récupération du compte utilsateur
            $user = $this->getUser();
            // récupération du profile rédacteur à partir du compte utilsateur
            $writer = $this->writerRepository->findByUser($user);
            // récupération des articles du profile rédacteur
            $articles = $writer->getArticles();
        }

        return $this->render('admin_article/index.html.twig', [
            // envoi de la liste des articles à la vue
            'articles' => $articles,
        ]);
    }

    #[Route('/new', name: 'app_admin_article_new', methods: ['GET', 'POST'])]
    public function new(Request $request, ArticleRepository $articleRepository): Response
    {
        if (!$this->isGranted('ROLE_EDITOR') && !$this->isGranted('ROLE_WRITER')) {
            // l'utilisateur n'est ni éditeur ni réducteur , il ne peut pas créer de nouvel article 
            throw new AccessDeniedException();
        }

        $article = new Article();
        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $articleRepository->add($article, true);

            return $this->redirectToRoute('app_admin_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_article/new.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_article_show', methods: ['GET'])]
    public function show(Article $article): Response
    {
        $this->filterUser($article);

        return $this->render('admin_article/show.html.twig', [
            'article' => $article,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_article_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Article $article, ArticleRepository $articleRepository): Response
    {
        $this->filterUser($article);

        $form = $this->createForm(ArticleType::class, $article);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $articleRepository->add($article, true);

            return $this->redirectToRoute('app_admin_article_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('admin_article/edit.html.twig', [
            'article' => $article,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_article_delete', methods: ['POST'])]
    public function delete(Request $request, Article $article, ArticleRepository $articleRepository): Response
    {
        $this->filterUser($article);

        if ($this->isCsrfTokenValid('delete' . $article->getId(), $request->request->get('_token'))) {
            $articleRepository->remove($article, true);
        }

        return $this->redirectToRoute('app_admin_article_index', [], Response::HTTP_SEE_OTHER);
    }

    private function filterUser(Article $article)
    {
        // les utilisateurs non authentifiés sont renvoyés vers la page de login
        $this->denyAccessUnlessGranted('IS_AUTHENTICATED_FULLY');

        // méthode alternative à la méthode denyAccessUnlessGranted()
        // if (!$this->isGranted('IS_AUTHENTICATED_FULLY')) {
        //     l'utilisateur n'est pas authentifié
        //     throw new AccessDeniedException();
        // }

        if (!$this->isGranted('ROLE_EDITOR') && $this->isGranted('ROLE_WRITER')) {
            $user = $this->getUser();
            $writer = $this->writerRepository->findByUser($user);
            $articles = $writer->getArticles();
            if (!$articles->contains($article)) {
                // le rédacteur n'est pas auteur de l'article
                throw new NotFoundHttpException();
            }
        }
    }

}

templates/admin_article/_delete_form.html.twig
<form method="post" action="{{ path('app_admin_article_delete', {'id': article.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ article.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/admin_article/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/admin_article/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Article{% endblock %}

{% block body %}
    <h1>Edit Article</h1>

    {{ include('admin_article/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_admin_article_index') }}">back to list</a>

    {{ include('admin_article/_delete_form.html.twig') }}
{% endblock %}

templates/admin_article/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article index{% endblock %}

{% block body %}
    <h1>Article index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Body</th>
                <th>Published_at</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for article in articles %}
            <tr>
                <td>{{ article.id }}</td>
                <td>{{ article.title }}</td>
                <td>{{ article.body }}</td>
                <td>{{ article.publishedAt ? article.publishedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_admin_article_show', {'id': article.id}) }}">show</a>
                    <a href="{{ path('app_admin_article_edit', {'id': article.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% if is_granted('ROLE_EDITOR') or is_granted ('ROLE_WRITER') %}
    <a href="{{ path('app_admin_article_new') }}">Create new</a>
    {% endif %}
{% endblock %}

templates/admin_article/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Article{% endblock %}

{% block body %}
    <h1>Create new Article</h1>

    {{ include('admin_article/_form.html.twig') }}

    <a href="{{ path('app_admin_article_index') }}">back to list</a>
{% endblock %}

templates/admin_article/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Article{% endblock %}

{% block body %}
    <h1>Article</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ article.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ article.title }}</td>
            </tr>
            <tr>
                <th>Body</th>
                <td>{{ article.body }}</td>
            </tr>
            <tr>
                <th>Published_at</th>
                <td>{{ article.publishedAt ? article.publishedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_admin_article_index') }}">back to list</a>

    <a href="{{ path('app_admin_article_edit', {'id': article.id}) }}">edit</a>

    {{ include('admin_article/_delete_form.html.twig') }}
{% endblock %}